name: Build Awesome Copilot Index

on:
  # Run on push to main branch
  push:
    branches: [ master ]
  # Run daily at 6 AM UTC to keep index fresh
  schedule:
    - cron: '0 6 * * *'
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: 'latest'

      - name: Cache Babashka dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: bb-deps-${{ hashFiles('bb.edn') }}
          restore-keys: bb-deps-

      - name: Download awesome-copilot repository
        run: bb download-awesome!

      - name: Generate index files
        run: bb generate-index!

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.json index.edn
          git diff --staged --quiet || git commit -m "Update index files"
          git push
