name: Build Awesome Copilot Index

on:
  # Run on push to main branch
  push:
    branches: [ master ]
  # Run daily at 6 AM UTC to keep index fresh
  schedule:
    - cron: '0 6 * * *'
  # Allow manual triggering
  workflow_dispatch:

# Required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Only allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: 'latest'

      - name: Cache Babashka dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: bb-deps-${{ hashFiles('bb.edn') }}
          restore-keys: bb-deps-

      - name: Download awesome-copilot repository
        run: bb download-awesome

      - name: Generate index files
        run: bb generate-index

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create pages directory structure
        run: |
          mkdir -p _site
          cp index.json _site/
          cp index.edn _site/
          cp index.md _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
