name: Build Awesome Copilot Index

on:
  push:
    branches: [ master ]
  # Run daily at 6 AM UTC to keep index fresh
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:


permissions:
  pages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: 'latest'

      - name: Cache Babashka dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
            .cpcache
          key: bb-deps-${{ hashFiles('bb.edn') }}
          restore-keys: bb-deps-

      - name: Download awesome-copilot repository
        run: bb download-awesome

      - name: Generate index files
        run: bb generate-index

      - name: Create pages directory structure
        run: |
          mkdir -p _site
          cp site/awesome-copilot.json _site/
          cp site/awesome-copilot.edn _site/
          cp site/index.md _site/

      - name: Deploy app to gh-pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          enable_jekyll: true